--CREATE DATABASE DBACCOUNT

--USE DBACCOUNT

--CREATE TABLE TBLEMPLOYEE
--(
--ID TINYINT IDENTITY(1,1) PRIMARY KEY,
--FULLNAME VARCHAR(60)
--)

--CREATE TABLE TBLCATEGORIES
--(
--ID TINYINT IDENTITY(1,1) PRIMARY KEY,
--TITLE VARCHAR(25)
--)

--CREATE TABLE TBLCITIES
--(
--ID TINYINT IDENTITY(1,1) PRIMARY KEY,
--CITYNAME VARCHAR(35)
--)

--CREATE TABLE TBLCLIENTS
--(
--ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
--FIRSTNAME VARCHAR(25),
--LASTNAME VARCHAR(25),
--CITYID TINYINT,
--BALANCE DECIMAL(18,2)
--FOREIGN KEY (CITYID) REFERENCES TBLCITIES(ID)
--)


--CREATE TABLE TBLPRODUCTS
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--PRODUCTNAME VARCHAR(35),
--BRANDNAME VARCHAR(35),
--CATEGORYID TINYINT,
--COSTPRICE DECIMAL(18,2),
--SELLPRICE DECIMAL(18,2),
--STOCKLEVEL SMALLINT CHECK(STOCKLEVEL>0),
--STOCKSTATUS BIT DEFAULT '1',
--FOREIGN KEY (CATEGORYID) REFERENCES TBLCATEGORIES(ID)
--)

--TRUNCATE TABLE TBLPRODUCTS 

--ALTER TABLE TBLPRODUCTS
--ADD FOREIGN KEY (CATEGORYID) REFERENCES TBLCATEGORIES(ID)

--CREATE TABLE TBLSALES
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--PRODUCTID INT,
--CLIENTID SMALLINT,
--EMPLOYEEID TINYINT,
--QUANTITY SMALLINT,
--TOTAL DECIMAL(18,2),
--SOLDDATE SMALLDATETIME,
--FOREIGN KEY (PRODUCTID) REFERENCES TBLPRODUCTS(ID),
--FOREIGN KEY (CLIENTID) REFERENCES TBLCLIENTS(ID),
--FOREIGN KEY (EMPLOYEEID) REFERENCES TBLEMPLOYEE(ID)

--)