--CREATE DATABASE RELATIONS

--USE RELATIONS

--CREATE TABLE SPECIFICATIONS
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--PRODUCTHEIGHT VARCHAR(25),
--PRODYCTWEIGHT VARCHAR(25),
--)

--CREATE TABLE PRODUCTS
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--TITLE VARCHAR(25),
--PRICE DECIMAL (18,2),
--STOCK INT,
--SPECIFICATIONID INT UNIQUE
--)

--ALTER TABLE PRODUCTS
--ADD FOREIGN KEY(SPECIFICATIONID) REFERENCES SPECIFICATIONS(ID)
