--COUNT AND GROUP BY

--SELECT * FROM TblStudents

--SELECT COUNT(*) FROM TblStudents WHERE BirthCity='Manchester'

--UPDATE TblStudents SET BirthCity='Manchester' WHERE ID=35

--SELECT COUNT(*) AS 'STUDENTS' FROM TblStudents WHERE BirthCity='Manchester'

--SELECT BIRTHCITY,COUNT(*) AS 'STUDENTS' FROM TblStudents WHERE BirthCity='Manchester' GROUP BY BirthCity

--SELECT BIRTHCITY,COUNT(*) AS 'STUDENTS' FROM TblStudents GROUP BY BirthCity

--SUM / AVG / MIN / MAX

SELECT * FROM TblExams

--SELECT SUM(EXAMONE) AS 'EX_1_SUM',SUM(EXAMTWO) AS 'EX_2_SUM',SUM(EXAMTHREE) AS 'EX_3_SUM' FROM TblExams

--SELECT AVG(EXAMONE) AS 'EX_1_AVG',AVG(EXAMTWO) AS 'EX_2_AVG',AVG(EXAMTHREE) AS 'EX_3_AVG' FROM TblExams

--SELECT MAX(EXAMONE) AS 'EX_1_MAX',MAX(EXAMTWO) AS 'EX_2_MAX',MAX(EXAMTHREE) AS 'EX_3_MAX' FROM TblExams

--SELECT MIN(EXAMONE) AS 'EX_1_MIN',MIN(EXAMTWO) AS 'EX_2_MIN',MIN(EXAMTHREE) AS 'EX_3_MIN' FROM TblExams

--SELECT *,(EXAMONE+EXAMTWO+EXAMTHREE)/3 AS'AVERAGE' FROM TblExams

SELECT *,(EXAMONE+EXAMTWO+EXAMTHREE)/3 AS'AVERAGE' FROM TblExams WHERE (EXAMONE+EXAMTWO+EXAMTHREE)/3 <50

SELECT COUNT(*) FROM TblExams WHERE (EXAMONE+EXAMTWO+EXAMTHREE)/3 <50