--SELECT * FROM TblExams

--SELECT ABS(-85) AS 'ABSOLUTE NUMBER'

--SELECT POWER(2,2) AS 'CALCULATE POWER'

--SELECT SQRT(25) AS 'SQUARE FOOT'

--SELECT CEILING(5.25) -- => 6
--SELECT FLOOR(5.25) -- => 5

--SELECT CEILING(SQRT(SUM(Average))) FROM TblExams
--SELECT FLOOR(SQRT(SUM(Average))) FROM TblExams

--SELECT ABS((SELECT AVG(AVERAGE) FROM TblExams)-Average) AS 'ABSOLUTE NUMBERS' FROM TblExams

--SELECT AVG(ExamOne) AS'EXAMONE',SUM(EXAMTWO)/COUNT(*) AS'EXAMTWO',SUM(EXAMTHREE)/COUNT(*) AS'EXAMTHREEE'FROM TblExams


