--DECLARE @NEWVALUE INT
--SET @NEWVALUE=5
--SELECT @NEWVALUE AS 'RESULT'

--DECLARE @NEWNAME VARCHAR(25)
--SET @NEWNAME = 'MICHAEL'
--SELECT @NEWNAME AS 'NAME'

--DECLARE @ONEWEEKLATER SMALLDATETIME
--SET @ONEWEEKLATER = DATEADD(DAY,7,GETDATE())
--SELECT GETDATE() AS 'TODAY',@ONEWEEKLATER AS 'WEEK LATER'

--USE DBACCOUNT

--SELECT * FROM TBLPRODUCTS

--DECLARE @ALLSTOCK INT
--SET @ALLSTOCK = (SELECT SUM(STOCKLEVEL) FROM TBLPRODUCTS)
--SELECT @ALLSTOCK AS'WAREHOUSE STOCK'

--DECLARE @PRODUCTVARIETY SMALLINT
--SELECT @PRODUCTVARIETY = COUNT(*) FROM TBLPRODUCTS
--SELECT @PRODUCTVARIETY AS 'PRODUCT VARIETY'

