--CREATE PROCEDURE WEEKDAY_SALES
--@WEEKDAY VARCHAR(20)
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATENAME(WEEKDAY,SOLDDATE) = @WEEKDAY

--EXEC WEEKDAY_SALES 'MONDAY'

--CREATE PROCEDURE WEEKDAY_SALES
--@WEEKDAY VARCHAR(20)
--AS

--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATENAME(DAY,SOLDDATE) = '3'


--CREATE PROCEDURE MONTHLY_SALES
--@MONTH_NAME VARCHAR(20)
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATENAME(MONTH,SOLDDATE) = @MONTH_NAME

--EXEC MONTHLY_SALES 'DECEMBER'

--CREATE PROCEDURE YEARLY_SALES
--@YEAR VARCHAR(20)
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATENAME(YEAR,SOLDDATE) = @YEAR

--EXEC YEARLY_SALES '2024'

--01.06.2023
--DAY/MONTH/YEAR


--CREATE PROCEDURE FIRST_WEEK_SALES
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATEPART(DAY,SOLDDATE) BETWEEN 1 AND 7 

--EXEC FIRST_WEEK_SALES

--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATEPART(MONTH,SOLDDATE) BETWEEN 10 AND 12 

--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATEPART(YEAR,SOLDDATE) = 2023


--CREATE PROCEDURE DATE_DIFF 
--@VALUE TINYINT
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE DATEDIFF(DAY,SOLDDATE,GETDATE()) < @VALUE

--SELECT DATEDIFF(DAY,'2024.01.01',GETDATE())

--EXEC DATE_DIFF 17


-- 30 DAYS CREDIT TERM
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CLIENT NAME', 
--PRODUCTNAME AS 'PRODUCT NAME',
--BRANDNAME AS 'BRAND NAME',
--QUANTITY,
--TOTAL AS 'BALANCE',
--SOLDDATE AS'DATE',
--DATEADD(MONTH,2,SOLDDATE) AS 'TERMS'
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID

