-- AND - OR

--SELECT * FROM TblStudents WHERE BirthCity LIKE 'B%' OR BirthCity LIKE '%M'

--SELECT CLUB,COUNT(*) AS 'STUDENTS' FROM TblStudents WHERE CLUB LIKE 'M%' AND CLUB LIKE '%I_' GROUP BY CLUB ORDER BY CLUB DESC 

--IN NOT IN 

--SELECT * FROM TblStudents WHERE CLUB = 'CHESS' OR CLUB = 'MATH' OR CLUB = 'MUSIC'

--SELECT * FROM TblStudents WHERE CLUB IN ('CHESS','MATH','MUSIC')

--SELECT * FROM TblStudents WHERE CLUB NOT IN ('CHESS','MATH','MUSIC')

-- BETWEEN

--SELECT * FROM TblExams WHERE ExamOne > 45 AND EXAMONE < 95

--SELECT * FROM TblExams WHERE ExamOne BETWEEN 45 AND 95 

--SELECT * FROM TblStudents WHERE BirthCity BETWEEN 'M' AND 'Z'
--SELECT * FROM TblStudents WHERE BirthCity BETWEEN 'E' AND 'M'