--UPDATE TBLCLIENTS SET BALANCE=(SELECT SUM(TOTAL) FROM TBLSALES WHERE CLIENTID = 6) WHERE ID = 6
--UPDATE TBLPRODUCTS SET STOCKLEVEL = STOCKLEVEL - (SELECT SUM(QUANTITY) FROM TBLSALES WHERE PRODUCTID=11) 
--WHERE ID=11

--SELECT SUM(BALANCE) FROM TBLCLIENTS

--SELECT SUM(TOTAL) FROM TBLSALES

