--SELECT @@LANGUAGE, @@VERSION, @@SERVERNAME, @@LANGID, @@MAX_CONNECTIONS

--SELECT 5

--DECLARE @NUMBERONE INT
--DECLARE @NUMBERTWO INT
--DECLARE @TOTAL INT

--SET @NUMBERONE = 5
--SET @NUMBERTWO = 7
--SET @TOTAL = @NUMBERONE * @NUMBERTWO

--PRINT 'THIS IS A CALCULATION'
--PRINT '----------------------'
--PRINT @TOTAL

--DECLARE @TEMPTABLE TABLE
--(
--ID INT,
--PRODUCT VARCHAR(25),
--TOTALAMOUNT DECIMAL(18,2)
--)

--INSERT INTO @TEMPTABLE (ID,PRODUCT,TOTALAMOUNT) VALUES (1,'PENCIL',25)

--SELECT * FROM @TEMPTABLE

--ALTER TRIGGER [dbo].[TOTAL_AMOUNT_MAKER]
--ON [dbo].[TBLSALES]
--AFTER INSERT
--AS
--BEGIN

--DECLARE @ID_TABLE TABLE
--(
--ID INT,
--PRODUCTID INT
--)

--INSERT INTO @ID_TABLE (ID,PRODUCTID)
--VALUES ((SELECT ID FROM INSERTED),(SELECT PRODUCTID FROM INSERTED))



--DECLARE @NEWSELLPRICE DECIMAL(18,2)
--SELECT @NEWSELLPRICE = SELLPRICE FROM TBLPRODUCTS WHERE ID = (SELECT PRODUCTID FROM @ID_TABLE)

--UPDATE TBLSALES SET TOTAL = QUANTITY*@NEWSELLPRICE WHERE ID = (SELECT ID FROM @ID_TABLE)

--END
