--CREATE TABLE THIRD_TABLE
--(
--ID INT IDENTITY(1,1),
--TITLE VARCHAR(25)
--)

--INSERT INTO FIRST_TABLE (TITLE) VALUES (14)

--INSERT INTO SECOND_TABLE (TITLE) VALUES ('TEST5')

--SELECT * FROM SECOND_TABLE INNER JOIN FIRST_TABLE ON SECOND_TABLE.ID = FIRST_TABLE.ID

--DELETE FROM SECOND_TABLE WHERE ID = 4

--SELECT * FROM SECOND_TABLE INNER JOIN FIRST_TABLE ON SECOND_TABLE.ID = FIRST_TABLE.ID -- INNER JOIN

--SELECT * FROM SECOND_TABLE LEFT JOIN FIRST_TABLE ON SECOND_TABLE.ID = FIRST_TABLE.ID  -- LEFT JOIN

--SELECT * FROM SECOND_TABLE RIGHT JOIN FIRST_TABLE ON SECOND_TABLE.ID = FIRST_TABLE.ID -- RIGHT JOIN

--SELECT * FROM SECOND_TABLE FULL JOIN FIRST_TABLE ON SECOND_TABLE.ID = FIRST_TABLE.ID

--SELECT * FROM TblStudents FULL JOIN TblCities ON TblStudents.CityId = TblCities.ID

--SELECT * FROM TblCities UNION SELECT * FROM SECOND_TABLE

