--CREATE DATABASE M2M
--USE M2M
--CREATE TABLE USERS
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--FULLNAME VARCHAR(50),
--)

--CREATE TABLE CLAIMS
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--TITLE VARCHAR(50),
--)

--CREATE TABLE USERCLAIMS
--(
--ID INT IDENTITY(1,1) PRIMARY KEY,
--USERID INT,
--CLAIMID INT,
--FOREIGN KEY (USERID) REFERENCES USERS(ID),
--FOREIGN KEY (CLAIMID) REFERENCES CLAIMS(ID),
--)

--SELECT FULLNAME,TITLE FROM USERCLAIMS 
--INNER JOIN USERS ON USERCLAIMS.USERID = USERS.ID
--INNER JOIN CLAIMS ON USERCLAIMS.CLAIMID = CLAIMS.ID
--WHERE TITLE = 'PURCHASE'