--INDEX / CLUSTERED INDEX - NON CLUSTERED INDEX

--CREATE TABLE TEST 
--(
--ID INT IDENTITY (1,1),
--TITLE VARCHAR(50)
--)

--DECLARE @NUMBER INT = 1
--WHILE @NUMBER<250001
--BEGIN
--	INSERT INTO TEST (TITLE) VALUES ('NUMBER: '+ CAST(@NUMBER AS VARCHAR))
--	SET @NUMBER+=1
--END

--SELECT * FROM TEST WHERE ID = 249999

--CREATE CLUSTERED INDEX ID_INDEX
--ON TEST(ID)

--SELECT * FROM TEST WHERE TITLE = 'NUMBER: 249999'