--UPDATE TBLSALES SET 
--TOTAL=(
--SELECT QUANTITY*SELLPRICE 
--FROM TBLSALES INNER JOIN TBLPRODUCTS 
--ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--WHERE TBLSALES.ID=14
--)
--WHERE ID = 14

--CREATE PROCEDURE SALES_ACTION
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CUSTOMER NAME', 
--PRODUCTNAME AS 'PRODUCT',
--BRANDNAME AS 'BRAND',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID

--EXECUTE SALES_ACTION

--EXEC SALES_ACTION

--CREATE PROCEDURE TEST
--AS
--SELECT * FROM TBLCATEGORIES

--EXEC TEST

--DROP PROCEDURE TEST

--CREATE PROCEDURE SALES_ACTION_BYCITY
--@VALUE VARCHAR(35)
--AS
--SELECT SUBSTRING(FIRSTNAME,1,1)+'.'+LASTNAME AS 'CUSTOMER NAME', 
--PRODUCTNAME AS 'PRODUCT',
--BRANDNAME AS 'BRAND',
--QUANTITY,
--TOTAL,
--SOLDDATE AS'DATE' 
--FROM TBLSALES 
--INNER JOIN TBLPRODUCTS ON TBLSALES.PRODUCTID = TBLPRODUCTS.ID 
--INNER JOIN TBLCLIENTS ON TBLSALES.CLIENTID = TBLCLIENTS.ID
--INNER JOIN TBLEMPLOYEE ON TBLSALES.EMPLOYEEID = TBLEMPLOYEE.ID
--WHERE CITYID = (SELECT ID FROM TBLCITIES WHERE CITYNAME = @VALUE)

--EXEC SALES_ACTION_BYCITY 'MANCHESTER'